### ISSUE TITLE
Gate crashes server

### ISSUE THREAD

**Issue by paintballkev812** [AbrarSyed/SecretRoomsMod-forge#131]
MC: 1.7.2
Forge: 1065
Secret rooms: 345

The gate can crash the game, once it crashes, I cannot reconnect to the world, I get an error message. The crash seems to be intermittent. It can happen when opening/closing the gate or when the gate is destroyed

Here is a recording showing the crash. I know this is not how gates are used, but I did not have time to record gameplay until it happened so I recorded this.

http://youtu.be/eWHmiRLKVKw

This may be related to the Railcraft mod.

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/5/14 9:04 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.minecraft.block.BlockGrass.func_149720_d(BlockGrass.java:135)
    at com.github.abrarsyed.secretroomsmod.blocks.BlockCamoFull.func_149720_d(BlockCamoFull.java:205)
    at com.github.abrarsyed.secretroomsmod.client.BlockRenderer.renderFullCamo(BlockRenderer.java:189)
    at com.github.abrarsyed.secretroomsmod.client.BlockRenderer.renderWorldBlock(BlockRenderer.java:57)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:293)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:180)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1522)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1175)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1010)
    at net.minecraft.client.Minecraft.func_71411_J(MinecraftOverlay.java:944)
    at net.minecraft.client.Minecraft.func_99999_d(MinecraftOverlay.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.block.BlockGrass.func_149720_d(BlockGrass.java:135)
    at com.github.abrarsyed.secretroomsmod.blocks.BlockCamoFull.func_149720_d(BlockCamoFull.java:205)
    at com.github.abrarsyed.secretroomsmod.client.BlockRenderer.renderFullCamo(BlockRenderer.java:189)
    at com.github.abrarsyed.secretroomsmod.client.BlockRenderer.renderWorldBlock(BlockRenderer.java:57)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:293)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:180)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1522)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1175)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['paint812'/413, l='MpServer', x=-191.05, y=69.62, z=272.54]]
    Chunk stats: MultiplayerChunkCache: 45, 45
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-193,64,268), Chunk: (at 15,4,12 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 651 game time, 651 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 43 total; [EntityClientPlayerMP['paint812'/413, l='MpServer', x=-191.05, y=69.62, z=272.54], EntitySquid['Squid'/279, l='MpServer', x=-149.41, y=60.00, z=251.66], EntitySquid['Squid'/278, l='MpServer', x=-155.56, y=60.94, z=251.22], EntitySquid['Squid'/283, l='MpServer', x=-155.69, y=62.28, z=243.44], EntitySquid['Squid'/282, l='MpServer', x=-146.84, y=60.00, z=251.81], EntitySquid['Squid'/281, l='MpServer', x=-153.66, y=61.34, z=255.22], EntitySquid['Squid'/280, l='MpServer', x=-146.16, y=61.38, z=246.50], EntitySquid['Squid'/286, l='MpServer', x=-148.75, y=60.00, z=264.91], EntityBat['Bat'/192, l='MpServer', x=-220.44, y=24.91, z=305.22], EntitySquid['Squid'/285, l='MpServer', x=-159.44, y=59.00, z=250.56], EntitySquid['Squid'/284, l='MpServer', x=-159.09, y=60.38, z=245.63], EntitySkeleton['Skeleton'/220, l='MpServer', x=-203.50, y=41.00, z=322.50], EntityChicken['Chicken'/216, l='MpServer', x=-207.53, y=68.00, z=292.53], EntitySquid['Squid'/262, l='MpServer', x=-172.75, y=61.84, z=246.41], EntitySpider['Spider'/217, l='MpServer', x=-196.38, y=41.13, z=321.72], EntitySquid['Squid'/263, l='MpServer', x=-163.50, y=60.16, z=242.16], EntitySkeleton['Skeleton'/218, l='MpServer', x=-201.84, y=41.00, z=322.56], EntitySquid['Squid'/260, l='MpServer', x=-171.06, y=61.34, z=250.91], EntitySkeleton['Skeleton'/219, l='MpServer', x=-204.50, y=41.00, z=321.50], EntitySquid['Squid'/261, l='MpServer', x=-167.88, y=60.34, z=249.75], EntitySheep['Sheep'/212, l='MpServer', x=-206.34, y=64.00, z=283.53], EntitySheep['Sheep'/213, l='MpServer', x=-200.50, y=66.00, z=294.50], EntitySheep['Sheep'/214, l='MpServer', x=-195.69, y=68.00, z=288.53], EntityChicken['Chicken'/215, l='MpServer', x=-196.53, y=67.00, z=295.47], EntityItem['item.tile.fungusStinkhorn'/209, l='MpServer', x=-198.91, y=67.13, z=256.13], EntitySheep['Sheep'/210, l='MpServer', x=-201.47, y=66.00, z=286.50], EntityChicken['Chicken'/211, l='MpServer', x=-200.69, y=71.00, z=281.53], EntityCreeper['Creeper'/239, l='MpServer', x=-187.50, y=37.00, z=315.50], EntityChicken['Chicken'/238, l='MpServer', x=-190.25, y=70.03, z=283.63], EntityCreeper['Creeper'/237, l='MpServer', x=-184.00, y=32.00, z=267.44], EntityZombie['Zombie'/236, l='MpServer', x=-180.50, y=31.00, z=267.50], EntityZombie['Zombie'/235, l='MpServer', x=-184.50, y=15.00, z=253.50], EntityBat['Bat'/167, l='MpServer', x=-239.59, y=24.00, z=302.53], EntityZombie['Zombie'/186, l='MpServer', x=-239.50, y=35.00, z=331.50], EntityBat['Bat'/184, l='MpServer', x=-239.44, y=24.13, z=307.03], EntityZombie['Zombie'/185, l='MpServer', x=-234.75, y=32.00, z=331.13], EntityItem['item.tile.fungusParasol'/291, l='MpServer', x=-132.47, y=63.13, z=267.88], EntitySkeleton['Skeleton'/182, l='MpServer', x=-239.56, y=11.00, z=317.06], EntityBat['Bat'/183, l='MpServer', x=-235.16, y=24.06, z=307.50], EntityBat['Bat'/180, l='MpServer', x=-229.75, y=25.09, z=300.75], EntityCreeper['Creeper'/240, l='MpServer', x=-187.50, y=37.00, z=316.50], EntityZombie['Zombie'/181, l='MpServer', x=-236.50, y=23.00, z=303.50], EntityCreeper['Creeper'/241, l='MpServer', x=-186.28, y=37.00, z=320.31]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:368)
    at net.minecraft.client.Minecraft.func_71396_d(MinecraftOverlay.java:2382)
    at net.minecraft.client.Minecraft.func_99999_d(MinecraftOverlay.java:864)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1574008752 bytes (1501 MB) / 2122842112 bytes (2024 MB) up to 2122842112 bytes (2024 MB)
    JVM Flags: 2 total; -Xmx2048m -Xms2048m
    Mod Pack: Unknown / None
    LiteLoader Mods: 1 loaded mod(s)
          - Note Block Display version 1.3
    LaunchWrapper: 21 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: lain.mods.littlefix.LittleFixTransformer
          - Transformer: joserichi.skullsplus.common.core.SkullClassTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.ChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: xaero.mods.noteblockdisplay.BlockActionPacketTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.core.transformers.CustomPayloadPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    AABB Pool Size: 9254 (518224 bytes; 0 MB) allocated, 2 (112 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.03 FML v7.2.165.1065 Minecraft Forge 10.12.1.1065 32 mods loaded, 32 mods active
    mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    FML{7.2.165.1065} [Forge Mod Loader] (forge-1.7.2-10.12.1.1065-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    Forge{10.12.1.1065} [Minecraft Forge] (forge-1.7.2-10.12.1.1065-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    LittleFix{1.7.2-v1} [LittleFix] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    ChickenShed{1.1.3} [Chicken Shed] ([1.7.2] ChickenShed (v1.1.3).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    DC1{3.3.2.18} [KingCore] ([1.7.2] KingCore v3.3.2.18 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    FishingNets{1.1.1.3} [Fishing Nets] ([1.7.2M] FishingNets v1.1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    ToolHeads{1.1.1.3} [Tool Heads] ([1.7.2M] ToolHeads v1.1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    Backpack{2.0.0-pre1} [Backpack] (backpack-2.0.0-pre1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    BiblioCraft{1.7.1} [BiblioCraft] (BiblioCraft[1.7.1][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    extrabuttons{1.7.2.0} [ExtraButtons] (extrabuttons-1.7.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    ForgeMultipart{1.1.0.282} [Forge Multipart] (ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    McMultipart{1.1.0.282} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    HopperDuctMod{1.3} [Hopper Ducts] (hopperductmod-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    modularpots{1.7.2.12} [Modular Flower Pots] (ModularPots-1.7.2.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    Morpheus{1.7.2-1.@MINOR.3} [Morpheus] (morpheus-1.7.2-1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    cfm{3.2.9.2} [§6MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.2.9.2-beta-build2(1.7.2) (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    MumbleLink{4.1.0} [MumbleLink for Forge] (MumbleLink-1.7.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    ExtendedPASupport{1.0.0} [ExtendedPASupport for MumbleLink] (MumbleLink-1.7.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    ObsidianBoat{v1.3.2} [Obsidian Boat] (ObsidianBoat-1.7.2-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    clayspawn{1.7.2a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.7.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    plantmegapack{3.00.09} [Plant Mega Pack] (Plant Mega Pack-1.7.2-3.00.09.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    Railcraft{9.0.0.0} [Railcraft] (Railcraft_1.7.2-9.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    RedstonePasteMod{1.6.1} [Redstone Paste] (RedstonePasteMod-1.7.2-1.6.1 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    RopesPlus{1.6.1} [Ropes+] (RopePlus-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    secretroomsmod{@VERSION@} [The SecretRoomsMod] (secretroomsmod-1.7.2-4.6.3.346.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    SkullsPlus{1.7.2-a} [SkullsPlus] (SkullsPlus-1.7.2-a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    wuppy29_slimedungeon{1.6.0} [Slime Dungeons] (Slime Dungeons 1.6.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    carystanley_soup{1.0} [Soup Mod] (soup_mod-1.7.2-v1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    taverns{2.2.1-0} [Village Taverns] (VillageTaverns-2.2.1-0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    VNE{1.0.1} [Villagers Need Emeralds!] (VNE-1.7.2-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    ForgeMicroblock{1.1.0.282} [Forge Microblocks] (ForgeMultipart-1.7.2-1.1.0.282-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available
    Launched Version: 1.7.2
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 6700 Series   GL version 4.1.10750 Compatibility Profile Context, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 46 (2576 bytes; 0 MB) allocated, 39 (2184 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

```
[21:11:06] [Client thread/ERROR]: Error in packet handling!
io.netty.handler.codec.DecoderException: java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:71) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197) [ef.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [biy.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(MinecraftOverlay.java:1541) [azd.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(MinecraftOverlay.java:916) [azd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(MinecraftOverlay.java:835) [azd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:103) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
Caused by: java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo
    at com.github.abrarsyed.secretroomsmod.network.PacketCamo.actionClient(PacketCamo.java:49) ~[PacketCamo.class:?]
    at com.github.abrarsyed.secretroomsmod.network.PacketManager.actionClient(PacketManager.java:85) ~[PacketManager.class:?]
    at com.github.abrarsyed.secretroomsmod.network.PacketManager.decodeInto(PacketManager.java:73) ~[PacketManager.class:?]
    at com.github.abrarsyed.secretroomsmod.network.PacketManager.decodeInto(PacketManager.java:35) ~[PacketManager.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:75) ~[FMLIndexedMessageToMessageCodec.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:16) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 18 more
[21:11:06] [Client thread/ERROR]: There was a critical exception handling a packet on channel SecretRooms
io.netty.handler.codec.DecoderException: java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:71) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197) [ef.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [biy.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(MinecraftOverlay.java:1541) [azd.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(MinecraftOverlay.java:916) [azd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(MinecraftOverlay.java:835) [azd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:103) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_55]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_55]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_55]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
Caused by: java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo
    at com.github.abrarsyed.secretroomsmod.network.PacketCamo.actionClient(PacketCamo.java:49) ~[PacketCamo.class:?]
    at com.github.abrarsyed.secretroomsmod.network.PacketManager.actionClient(PacketManager.java:85) ~[PacketManager.class:?]
    at com.github.abrarsyed.secretroomsmod.network.PacketManager.decodeInto(PacketManager.java:73) ~[PacketManager.class:?]
    at com.github.abrarsyed.secretroomsmod.network.PacketManager.decodeInto(PacketManager.java:35) ~[PacketManager.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:75) ~[FMLIndexedMessageToMessageCodec.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:16) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    ... 18 more
[21:11:06] [Server thread/INFO]: paint812 lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.lang.ClassCastException: net.minecraft.network.NetHandlerPlayServer cannot be cast to net.minecraft.network.play.INetHandlerPlayClient], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[21:11:06] [Server thread/INFO]: paint812 left the game
[21:11:06] [Server thread/INFO]: Stopping singleplayer server as player logged out
[21:11:06] [Server thread/INFO]: Stopping server
[21:11:06] [Server thread/INFO]: Saving players
[21:11:06] [Server thread/INFO]: Saving worlds
[21:11:06] [Server thread/INFO]: Saving chunks for level 'New World-'/Overworld
[21:11:06] [Server thread/INFO]: Saving chunks for level 'New World-'/Nether
[21:11:06] [Server thread/INFO]: Saving chunks for level 'New World-'/The End
[21:11:07] [Server thread/INFO]: Unloading dimension 0
[21:11:07] [Server thread/INFO]: Unloading dimension -1
[21:11:07] [Server thread/INFO]: Unloading dimension 1

```

**Comment by AbrarSyed** [comment]
This issue may have already been fixed. I ask that you guys check real quick to see if it persists.
The log provided above is no longer useful as it is extremely out of date.
