### ISSUE TITLE
Server Crash/World not fully loaded

### ISSUE THREAD

**Issue by RamTam** [AbrarSyed/SecretRoomsMod-forge#152]
Hi, 

I just updated minecraft to 1.7.2 using forge 1.7.2-10.12.2.1147.
The SecretRoomsMod version is 4.7.0.370.
 First everything seems fine but after the login/spawn the world can not load fully and I'm falling into the long dark. 
Server crash report says this:

Time: 11/3/14 6:55 PM
Description: Ticking entity

java.lang.IllegalArgumentException: TileEntity data is NULL!
	at com.github.abrarsyed.secretroomsmod.network.PacketCamo.<init>(PacketCamo.java:43)
	at com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo.func_145844_m(TileEntityCamo.java:84)
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.abrarsyed.secretroomsmod.network.PacketCamo.<init>(PacketCamo.java:43)
	at com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo.func_145844_m(TileEntityCamo.java:84)
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:276)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 207
	Entity Name: RamTamSpecial
	Entity's Exact location: 62.42, 77.00, 7.77
	Entity's Block location: World: (62,77,7), Chunk: (at 14,4,7 in 3,0; contains blocks 48,0,0 to 63,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

Best regards RamTamSpecial (Forumname: MCFUser563118)

**Comment by AbrarSyed** [comment]
duplicate #153
