### ISSUE TITLE
Several error in server console

### ISSUE THREAD

**Issue by TomPiXX** [AbrarSyed/SecretRoomsMod-forge#159]
Cauldron 1.7.10
ForgeML 7.10.85.1236
secretroomsmod-1.7.10-4.7.1.376

Log:
[00:00:33] [Server thread/WARN]: java.io.FileNotFoundException: .\MainWorld\MoCWyvernLair\SecretRooms-ownership.dat (Das System kann den angegebenen Pfad nicht finden)
[00:00:33] [Server thread/WARN]: 	at java.io.FileOutputStream.open(Native Method)
[00:00:33] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[00:00:33] [Server thread/WARN]: 	at java.io.FileOutputStream.<init>(Unknown Source)
[00:00:33] [Server thread/WARN]: 	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getDataOut(OwnershipManager.java:283)
[00:00:33] [Server thread/WARN]: 	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.saveWorld(OwnershipManager.java:245)
[00:00:33] [Server thread/WARN]: 	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.onWorldSave(OwnershipManager.java:208)
[00:00:33] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_138_OwnershipManager_onWorldSave_Save.invoke(.dynamic)
[00:00:33] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[00:00:33] [Server thread/WARN]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[00:00:33] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1053)
[00:00:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.save(CraftWorld.java:791)
[00:00:33] [Server thread/WARN]: 	at autosaveworld.threads.save.AutoSaveThread.saveWorldNormal(AutoSaveThread.java:190)
[00:00:33] [Server thread/WARN]: 	at autosaveworld.threads.save.AutoSaveThread.saveWorld(AutoSaveThread.java:181)
[00:00:33] [Server thread/WARN]: 	at autosaveworld.threads.save.AutoSaveThread.access$000(AutoSaveThread.java:33)
[00:00:33] [Server thread/WARN]: 	at autosaveworld.threads.save.AutoSaveThread$2.run(AutoSaveThread.java:141)
[00:00:33] [Server thread/WARN]: 	at autosaveworld.utils.SchedulerUtils$1.run(SchedulerUtils.java:48)
[00:00:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[00:00:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[00:00:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862)
[00:00:33] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[00:00:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[00:00:33] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[00:00:33] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by AbrarSyed** [comment]
same as #151
