### ISSUE TITLE
Wooden/Iron door crashing game

### ISSUE THREAD

**Issue by vitortexc** [AbrarSyed/SecretRoomsMod-forge#183]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 04/10/15 20:01
Description: Exception ticking world

java.lang.IllegalArgumentException: TileEntity data is NULL!
	at com.github.abrarsyed.secretroomsmod.network.PacketCamo.<init>(PacketCamo.java:44)
	at com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo.func_145844_m(TileEntityCamo.java:93)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.github.abrarsyed.secretroomsmod.network.PacketCamo.<init>(PacketCamo.java:44)
	at com.github.abrarsyed.secretroomsmod.blocks.TileEntityCamo.func_145844_m(TileEntityCamo.java:93)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:591)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:533)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:67)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:185)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Tex-'/306, l='New World', x=198,15, y=80,00, z=242,23]]
	Chunk stats: ServerChunkCache: 694 Drop: 0
	Level seed: 1573835402937211989
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (192,64,248), Chunk: (at 0,4,8 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 314 game time, 314 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 127069 (now: false), thunder time: 136657 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 207950528 bytes (198 MB) / 418570240 bytes (399 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	TooManyItems{1.7.10} [TooManyItems] (minecraft.jar) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Tex-'/306, l='New World', x=198,15, y=80,00, z=242,23]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Jardyn** [comment]
I'm having the same issue as this guy. It was fine for a while, but then I was wandering around away from my house, and the server crashed and is continually crashing whenever I try to join it again.

Any suggestions would be appreciated.

- Jardyn
