### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by CraftYourWay** [AbrarSyed/SecretRoomsMod-forge#186]
im getting a error and i have no idea why.

java.lang.NullPointerException: Unexpected error
	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.getOwner(OwnershipManager.java:125)
	at com.github.abrarsyed.secretroomsmod.common.OwnershipManager.isOwner(OwnershipManager.java:115)
	at com.github.abrarsyed.secretroomsmod.blocks.BlockCamoTrapDoor.getPickBlock(BlockCamoTrapDoor.java:429)
	at codechicken.nei.api.ItemInfo.getIdentifierItems(ItemInfo.java:492)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:42)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:163)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_461_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by CraftYourWay** [comment]
updated and now works hope it wont happen more
