### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by BuilderDan** [AbrarSyed/SecretRoomsMod-forge#195]
Server crashes, won't start:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SoundFixPatchingLoader (AmbientSounds v2.1.0 mc1.12.2.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  AppleCore (AppleCore-mc1.12.2-2.2.2.jar)
  LoadingPlugin (Quark-r1.3-115.jar)
  LittlePatchingLoader (LittleTiles v1.5.0-pre39 mc1.12.2.jar)
  TANLoadingPlugin (ToughAsNails-1.12-3.0.0.68-universal.jar)
  ComfortsLoadingPlugin (comforts-1.12.2-0.0.6.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2 (1).jar)
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.b128.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1 (1).jar)
  LibrarianLib Plugin (librarianlib-1.12-4.1.jar)
  CreativePatchingLoader (CreativeCore v1.9.4 mc1.12.2.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12-1.9 (1).jar)
  Extra Alchemy ASM (extraalchemy-0.3.6-release.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 11/11/17 12:33 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Secret Rooms 5 (secretroomsmod)
Caused by: java.lang.NoClassDefFoundError: com/wynprice/secretroomsmod/render/fakemodels/FakeBlockModel
	at com.wynprice.secretroomsmod.SecretBlocks.<clinit>(SecretBlocks.java:64)
	at com.wynprice.secretroomsmod.SecretItems.<clinit>(SecretItems.java:20)
	at com.wynprice.secretroomsmod.proxy.CommonProxy.preInit(CommonProxy.java:30)
	at com.wynprice.secretroomsmod.SecretRooms5.preInit(SecretRooms5.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.wynprice.secretroomsmod.render.fakemodels.FakeBlockModel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.IBakedModel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@7fcff1b9 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 47 more
Caused by: java.lang.RuntimeException: Attempted to load class cfy for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 49 more

A detailed walkthrough of the error, its code path and all known details is as follows:
--------------------------------------------------

**Comment by sofifreak** [comment]
I can confirm the issues


[crash-2017-11-11_14.40.13-server.txt](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1463772/crash-2017-11-11_14.40.13-server.txt)

**Comment by Wyn-Price** [comment]
Sorry about not noticing the earlier. I'm not a contributor to this page so I don't get notified when issues happen

**Comment by Wyn-Price** [comment]
Ok I know what then issue is. I can fix this for tommorow, just stay patient

**Comment by Wyn-Price** [comment]
OK good news. Ive managed to get to a pc so ill fix it now. New release should be up within the hour

**Comment by BuilderDan** [comment]
That's quite alright, that's why I made a comment on the mods actual curse page! Appreciate your work!

**Comment by Wyn-Price** [comment]
thanks! Ive figured out the issue and just doing triple checks now. Will upload straight after

**Comment by Wyn-Price** [comment]
Also with the way curseforge works, I get a mass email at midnight with all the activity. I live in the UK (time is currently 12:21 am which is why Ive only just figured out this problem existed

**Comment by BuilderDan** [comment]
Yep, it does that if you have numerous things you receive notifications from. And no worries, I was just worried that this would never be replied to like I've dealt with in the past with other mods.

**Comment by Wyn-Price** [comment]
Ok im building the fix now. It should be released very soon. Sorry to keep you waiting this long

**Comment by BuilderDan** [comment]
Its fine, just glad it's fixed!

**Comment by Wyn-Price** [comment]
Ok file up on curseforge [link here](https://minecraft.curseforge.com/projects/secretroomsmod/files/2499930)

**Comment by Wyn-Price** [comment]
also if you could close this issue, Im not OP so i cant do anything with the thread

**Comment by BuilderDan** [comment]
Will do, thanks! Testing now.
