### ISSUE TITLE
Gate Block rendering issues? (along with other things)

### ISSUE THREAD

**Issue by Akitori** [AbrarSyed/SecretRoomsMod-forge#197]
![2017-11-19_12 49 38](https://user-images.githubusercontent.com/24502131/32994187-7ae5bc62-cd29-11e7-9dba-fb093f31a203.png)
So I'm not certain entirely how the gateblock works, it's supposed to render a entire row of blocks, right? Well, mine currently isn't, shows some as vanished, others as not. 

Latest release, (just released even) with forge 2509. 

Also found a bug involving 2 items, one of which may not be a bug and a feature while the other certainly is a bug.

Feature?: Hidden daylight sensors aren't able to be inverted like the vanilla counterparts.

Bug: Secret Trapped Chest gives no redstone output at all.

**Comment by Wyn-Price** [comment]
what is the secret gate disguesed as. Also the secret daylight sensors are able to invert, but ill make sure now. Secret Trapped chests give +1 redstone output for how many people are using them. I havnt added comparator output yet but ill work on that

**Comment by Akitori** [comment]
Secret gate was grass block, but bug occurs on all blocks tested (vanilla and modded)

**Comment by Wyn-Price** [comment]
also regarding the gate, can you try putting the gate a somthing that dosnt have a full bounding box (like a torch) and activate it. then see if the non rendered blocks have the same bounding box

**Comment by Wyn-Price** [comment]
Ok i figured out what causes the non rendered blocks. Its when you stand in the way of the gate while activating it. Fixing now

**Comment by Wyn-Price** [comment]
also one last thing, could you check the logs and see if theres any errors

**Comment by Akitori** [comment]
Tested with gate block, gate block does not take bounding block of torch, its all cubed. 
Also for any errors in logs, none are popping up on console server side at least.

**Comment by Akitori** [comment]
Concerning thing to note, the gateblock parts (the long invisible blocks) don't disappear when the gate block is broken..is that intentional?

**Comment by Wyn-Price** [comment]
no its not. Ill fix that now

**Comment by Wyn-Price** [comment]
also can you look at the client logs, i think it might be an issue there

**Comment by Akitori** [comment]
Found something interesting.

`[13:24:38] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147234_a(NetHandlerPlayClient.java:774) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:40) ~[ij.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:13) ~[ij.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[13:24:38] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1214) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:54) ~[ih.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:11) ~[ih.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more`

This was in the client logs...Says something about packet updates and tile entities. Might be the thing you're looking for?

**Comment by Wyn-Price** [comment]
how often did you get this issue. Was it every time or did it not happen that often

**Comment by Akitori** [comment]
Happened twice in the log, I'm not sure of specifics, guessing when i used the gate blocks.

**Comment by Wyn-Price** [comment]
was it every time you used the gate blocks or randomly

**Comment by Akitori** [comment]
I would say randomly.

**Comment by Wyn-Price** [comment]
ok ive managed to replicate it multiple times. I found out what causes it but i cant figure out why

**Comment by Wyn-Price** [comment]
Ok i think ive come up with a solution to the first issue and have fixed the block breaking issue
Regarding the light detector:
![light-gif](https://user-images.githubusercontent.com/15876682/32995207-26308cb6-cd69-11e7-8151-bb9a94008487.gif)

**Comment by Akitori** [comment]
that's cool!

**Comment by Wyn-Price** [comment]
ok i also fixed the comparators
![comparator-gif](https://user-images.githubusercontent.com/15876682/32995497-4503726c-cd6d-11e7-9074-102368cf055e.gif)

**Comment by Wyn-Price** [comment]
@Akitori ok releasing a new version now. Should be uploaded soon
