### ISSUE TITLE
[1.12.2-5.3.0] NullPointerException: Batching Chunks 

### ISSUE THREAD

**Issue by CplPibald** [AbrarSyed/SecretRoomsMod-forge#231]
Upgraded my dedicated server (custom modpack) to use v5.3.0.  Now I get a client crash when I go near a chunk that has a SR wooden door and SR pressure plates.

```
java.lang.NullPointerException: Batching chunks
	at com.wynprice.secretroomsmod.base.interfaces.ISecretBlock.canRenderInLayer(ISecretBlock.java:251)
	at com.wynprice.secretroomsmod.base.BaseBlockDoor.canRenderInLayer(BaseBlockDoor.java:186)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:186)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)
```

Link to [full crash report](https://pastebin.com/NmpM4fLF).

**Comment by Wyn-Price** [comment]
Does [this](https://github.com/AbrarSyed/SecretRoomsMod-forge/files/1735173/secretroomsmod-1.12.2-5.3.1.jar.zip) fix it? (You'll only need to update clientside)

**Comment by Wyn-Price** [comment]
Are you able to test?

**Comment by CplPibald** [comment]
I think so.  No crash in the chunks in question with the 5.3.1 jar.

BTW I did have to update both client and server because of the version bump.

**Comment by Wyn-Price** [comment]
is the crash report the same?

**Comment by CplPibald** [comment]
The client did not crash with the 5.3.1 jar.  I think you solved it.  Thanks.

**Comment by Wyn-Price** [comment]
Ah ok thats good. I misread your response

**Comment by Wyn-Price** [comment]
One thing i will say, is that issue would be caused by either:
1. Chunk trying to render the block before the TileEntityData was sent to the client
2. A corrupted SecretRoomsMod block

Hopfully it isnt the latter, but make sure to check

**Comment by CplPibald** [comment]
New error in 5.3.1 with same secret wooden door, this time when I walked up to it.  This one looks like a compat issue with WAILA.

```
java.lang.NullPointerException: Unexpected error
	at com.wynprice.secretroomsmod.intergration.walia.SecretWaliaDataProvider.getWailaStack(SecretWaliaDataProvider.java:46)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:115)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_95_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
```

Just before the crash I noticed that the top half of the door had the texture taken from the block underneath, but the bottom half of the door had the purple/black "no texture" texture.  I had broken and re-placed that door using 5.3.1 about a half hour ago, then left the area and restarted the server.  

Let me know if you want a full crash report.

**Comment by Wyn-Price** [comment]
Could you try with the latest version on cureseforge? 

Also sorry for late reply, i didnt get any notifications

**Comment by CplPibald** [comment]
When I looked at the door the first time after server restart.

```
java.lang.NullPointerException: Unexpected error
	at com.wynprice.secretroomsmod.intergration.walia.SecretWaliaDataProvider.getWailaStack(SecretWaliaDataProvider.java:46)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:115)
	at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:73)
	at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:57)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
```

**Comment by Wyn-Price** [comment]
Regular stone where you didn't place it means somethings got corrupted. In the HWYLA addon, I'm blindly assuming that everythings ok, and not corrupted. Try replacing the door.

**Comment by CplPibald** [comment]
Broke and re-placed the door and no crash now. The only thing out of the ordinary is that when I first walked up to it, the bottom half was stone texture, but quickly changed to stone brick when I got close.

Thanks for your work on this!

**Comment by Wyn-Price** [comment]
It's fine! Glad this is sorted
