### ISSUE TITLE
Dedicated server instantly crashes

### ISSUE THREAD

**Issue by eyezzzzzzz** [AbrarSyed/SecretRoomsMod-forge#245]
**Optifine?**: Yes
**If so what version**: 1.12.2 D1
**Does adding/removing Optifine affect the issue?**: No

Description: Ticking block entity

java.lang.ClassCastException: com.wynprice.secretroomsmod.blocks.SecretChest cannot be cast to com.wynprice.secretroomsmod.base.BaseFakePressurePlate
	at com.wynprice.secretroomsmod.tileentity.TileEntitySecretPressurePlate.func_73660_a(TileEntitySecretPressurePlate.java:15)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by eyezzzzzzz** [comment]
I've managed to solve the issue by activating removeErroringEntities and removeErroringTileEntities in forge's cfg, but I'd like to understand how to fix it without removing

**Comment by Wyn-Price** [comment]
The block seems to have placed the wrong tileentity. Where you doing anything funky before the crash? Did you place a pressure plate / chest before the crash

**Comment by Wyn-Price** [comment]
@eyezzzzzzz if you wernt doing anything weird, can i close this?
