### ISSUE TITLE
Infinite recursion when loading world

### ISSUE THREAD

**Issue by E14** [AbrarSyed/SecretRoomsMod-forge#260]
Minecraft crashes apparently due to infinite recursion when loading the world... I _may_ have been rotating secret gate blocks with an EnderIO Wrench when the client first crashed...

**Optifine?**: No
**Does adding/removing Optifine affect the issue?**: Not tested
**Crash log**: https://paste.feed-the-beast.com/view/5781983c
**Crash log excerpt**:
```
// I blame Dinnerbone.

Time: 10/3/18 9:32 PM
Description: Exception while updating neighbours

java.lang.StackOverflowError: Exception while updating neighbours
	at net.minecraft.world.World.func_189509_E(World.java:224)
	at net.minecraft.world.World.func_175625_s(World.java:2381)
	at com.wynprice.secretroomsmod.base.interfaces.ISecretTileEntity.getMirrorState(ISecretTileEntity.java:108)
	at com.wynprice.secretroomsmod.base.interfaces.ISecretBlock.getState(ISecretBlock.java:70)
	at com.wynprice.secretroomsmod.blocks.SecretGate.destroyGate(SecretGate.java:109)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:97)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
	at com.wynprice.secretroomsmod.blocks.SecretGate.deactivateGate(SecretGate.java:100)
        (...)
```

**Comment by Wyn-Price** [comment]
This is a known issue. Im working on getting time to work on this mod. Once then ill fix this.

**Comment by Wyn-Price** [comment]
Possibly. If you can reload the world, just try not to do that. Ill try and work on a fix soon

**Comment by E14** [comment]
Yes, I was able to load the world in mcedit and delete the gate blocks :)
